Example 1:

Input: s = “aab”

Output: [ ["a","a","b"], ["aa","b"] ]	

Explanation: The first  answer is generated by  making three partitions. The second answer is generated by making two partitions.
 




class Solution {
public:
    vector<vector<string>> partition(string s) {
        vector<vector<string>> ans;
        vector<string> temp;
        backtrack(s,ans,temp,0);
        return ans;
    }
    void backtrack(string s , vector<vector<string>> &ans, vector<string> &temp, int index){
        // base case 
        if(index==s.size()){
            ans.push_back(temp);
        }
        //
        for(int i = index; i < s.size();i++){
            if(ispalindrome(s,index,i)){
                // push back the res
                temp.push_back(s.substr(index,i-index+1));
                backtrack(s,ans,temp,i+1);
                temp.pop_back();
            }
        }
    }
    bool ispalindrome(string s , int start , int end ){
        while(start<=end){
            if(s[start++]!=s[end--]){
                return false;
            }
           
        }
         return true;
    }
};
